eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10017/eureka/
server:
  port: 11018
spring:
  application:
    name: eurekaclient
    rabbitmq:
      host: localhost
        port: 5672
          username: guest
sleuth:
  sampler:
    percentage: 1.0
